"""Creación de la tabla Factura

Revision ID: b3ca9df3130c
Revises: 148cf55e6dd3
Create Date: 2024-08-22 21:37:31.145647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3ca9df3130c'
down_revision = '148cf55e6dd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto', sa.String(length=64), nullable=True),
    sa.Column('precio', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('factura', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_factura_precio'), ['precio'], unique=False)
        batch_op.create_index(batch_op.f('ix_factura_producto'), ['producto'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('factura', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_factura_producto'))
        batch_op.drop_index(batch_op.f('ix_factura_precio'))

    op.drop_table('factura')
    # ### end Alembic commands ###
